version: "3.9"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: sootio
    container_name: sootio
    ports:
      - "55774:55774"
    volumes:
      - sootio-data:/app/data  # Persist SQLite cache data
    networks:
      - sootio-network
    env_file:
      - .env
    environment:
      - NODE_ENV=production
      - LOG_LEVEL=error
      - MAX_WORKERS=4
      - POSTGRES_POOL_SIZE=10
      - MKVDRAMA_DIRECT_PROXY_URL=socks5h://100.104.177.44:1080
    #deploy:
      #resources:
        #limits:
          #cpus: '8'
         # memory: 24G
    restart: always

volumes:
  sootio-data:  # Named volume for persistent data

networks:
  sootio-network:
    driver: bridge
    name: sootio-network
